### ISSUE TITLE
Support google service account for server 2 server applications

### ISSUE THREAD

**Issue by canaz** [mtanda/grafana-google-calendar-datasource#12]
Hi
It would be nice if you can support google service accounts:
https://developers.google.com/identity/protocols/OAuth2ServiceAccount

With this model there is no need for the user to accept the api on a popup and hopefully the image in the alert email does not show a "Annotation query failed"-message anymore.

**Comment by canaz** [comment]
What kind of admin account do you need?

**Comment by mtanda** [comment]
I'm not sure, because I'm not admin.

This is just another trial.
https://github.com/mtanda/grafana-google-calendar-datasource/pull/13

I can't test it, but it may work...

You need to create service account, and download json file from google console.
Then, change `Access` to `Server (Default)`, specify the file path in datasource setting page.

**Comment by canaz** [comment]
Tested plugin from master branch.
Configuration seems to work: 
Enter path to service account file -> "Save & Test" -> "Testing..." -> "Data source is working"

But opening a dashboard with calendar annotation shows a red box with
"Annotation Query Failed
Metric request error"

**Comment by mtanda** [comment]
I should tell you one important point.
This backend code depends on 
https://github.com/grafana/grafana/commit/4533f22871c207764f704f6280a555febe4c7c50#diff-36fa1b3501cb9f21b877adee5dc840c5 .
To use plugin, you may need to use Grafana nightly build.

I guess the "Metric request error" is happen before response result, so the oauth2 client fail to get access token.
